<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="7" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-07-25T18:30:05 CDT" name="Ecommerce Application" finished-at="2024-07-25T18:31:27 CDT" duration-ms="82321">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidationTest.loginErrorValidation()[pri:0, instance:subhrajitbasakacademy.TestCases.ErrorValidationTest@4738a206]" name="loginErrorValidation" class="subhrajitbasakacademy.TestCases.ErrorValidationTest"/>
      </group> <!-- ErrorHandling -->
      <group name="Purchase">
        <method signature="EcommerceApplicationTest.submitOrder(java.util.HashMap)[pri:0, instance:subhrajitbasakacademy.TestCases.EcommerceApplicationTest@53976f5c]" name="submitOrder" class="subhrajitbasakacademy.TestCases.EcommerceApplicationTest"/>
      </group> <!-- Purchase -->
    </groups>
    <test started-at="2024-07-25T18:30:05 CDT" name="Submit Order" finished-at="2024-07-25T18:30:52 CDT" duration-ms="47156">
      <class name="subhrajitbasakacademy.TestCases.EcommerceApplicationTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:subhrajitbasakacademy.TestCases.EcommerceApplicationTest@53976f5c]" started-at="2024-07-25T18:30:05 CDT" name="launchApplication" finished-at="2024-07-25T18:30:13 CDT" duration-ms="7920" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:subhrajitbasakacademy.TestCases.EcommerceApplicationTest@53976f5c]" started-at="2024-07-25T18:30:13 CDT" name="submitOrder" data-provider="getData" finished-at="2024-07-25T18:30:25 CDT" duration-ms="12457" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Subsen#1989, product=ADIDAS ORIGINAL, email=subhrajitbasak66@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:subhrajitbasakacademy.TestCases.EcommerceApplicationTest@53976f5c]" started-at="2024-07-25T18:30:25 CDT" name="tearDown" finished-at="2024-07-25T18:30:25 CDT" duration-ms="239" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:subhrajitbasakacademy.TestCases.EcommerceApplicationTest@53976f5c]" started-at="2024-07-25T18:30:25 CDT" name="launchApplication" finished-at="2024-07-25T18:30:31 CDT" duration-ms="5775" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:subhrajitbasakacademy.TestCases.EcommerceApplicationTest@53976f5c]" started-at="2024-07-25T18:30:31 CDT" name="submitOrder" data-provider="getData" finished-at="2024-07-25T18:30:44 CDT" duration-ms="12550" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Subsen#1989, product=ZARA COAT 3, email=basaksubhrajit89@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:subhrajitbasakacademy.TestCases.EcommerceApplicationTest@53976f5c]" started-at="2024-07-25T18:30:44 CDT" name="tearDown" finished-at="2024-07-25T18:30:44 CDT" duration-ms="185" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:subhrajitbasakacademy.TestCases.EcommerceApplicationTest@53976f5c]" started-at="2024-07-25T18:30:44 CDT" name="launchApplication" finished-at="2024-07-25T18:30:49 CDT" duration-ms="5548" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="orderListValidationTest()[pri:0, instance:subhrajitbasakacademy.TestCases.EcommerceApplicationTest@53976f5c]" started-at="2024-07-25T18:30:49 CDT" name="orderListValidationTest" finished-at="2024-07-25T18:30:52 CDT" depends-on-methods="subhrajitbasakacademy.TestCases.EcommerceApplicationTest.submitOrder" duration-ms="2160" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orderListValidationTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:subhrajitbasakacademy.TestCases.EcommerceApplicationTest@53976f5c]" started-at="2024-07-25T18:30:52 CDT" name="tearDown" finished-at="2024-07-25T18:30:52 CDT" duration-ms="169" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- subhrajitbasakacademy.TestCases.EcommerceApplicationTest -->
    </test> <!-- Submit Order -->
    <test started-at="2024-07-25T18:30:53 CDT" name="Error Validation" finished-at="2024-07-25T18:31:27 CDT" duration-ms="34176">
      <class name="subhrajitbasakacademy.TestCases.ErrorValidationTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:subhrajitbasakacademy.TestCases.ErrorValidationTest@4738a206]" started-at="2024-07-25T18:30:53 CDT" name="launchApplication" finished-at="2024-07-25T18:30:59 CDT" duration-ms="6016" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="loginErrorValidation()[pri:0, instance:subhrajitbasakacademy.TestCases.ErrorValidationTest@4738a206]" started-at="2024-07-25T18:30:59 CDT" name="loginErrorValidation" finished-at="2024-07-25T18:31:00 CDT" duration-ms="1304" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at subhrajitbasakacademy.TestCases.ErrorValidationTest.loginErrorValidation(ErrorValidationTest.java:20)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:subhrajitbasakacademy.TestCases.ErrorValidationTest@4738a206]" started-at="2024-07-25T18:31:00 CDT" name="tearDown" finished-at="2024-07-25T18:31:00 CDT" duration-ms="217" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:subhrajitbasakacademy.TestCases.ErrorValidationTest@4738a206]" started-at="2024-07-25T18:31:00 CDT" name="launchApplication" finished-at="2024-07-25T18:31:06 CDT" duration-ms="5755" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="loginErrorValidation()[pri:0, instance:subhrajitbasakacademy.TestCases.ErrorValidationTest@4738a206]" started-at="2024-07-25T18:31:06 CDT" name="loginErrorValidation" finished-at="2024-07-25T18:31:08 CDT" duration-ms="1761" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password] but found [Incorrect email or password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password] but found [Incorrect email or password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at subhrajitbasakacademy.TestCases.ErrorValidationTest.loginErrorValidation(ErrorValidationTest.java:20)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:subhrajitbasakacademy.TestCases.ErrorValidationTest@4738a206]" started-at="2024-07-25T18:31:08 CDT" name="tearDown" finished-at="2024-07-25T18:31:09 CDT" duration-ms="216" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:subhrajitbasakacademy.TestCases.ErrorValidationTest@4738a206]" started-at="2024-07-25T18:31:09 CDT" name="launchApplication" finished-at="2024-07-25T18:31:14 CDT" duration-ms="5638" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="productErrorValidation()[pri:0, instance:subhrajitbasakacademy.TestCases.ErrorValidationTest@4738a206]" started-at="2024-07-25T18:31:14 CDT" name="productErrorValidation" finished-at="2024-07-25T18:31:27 CDT" duration-ms="12379" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- productErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:subhrajitbasakacademy.TestCases.ErrorValidationTest@4738a206]" started-at="2024-07-25T18:31:27 CDT" name="tearDown" finished-at="2024-07-25T18:31:27 CDT" duration-ms="179" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- subhrajitbasakacademy.TestCases.ErrorValidationTest -->
    </test> <!-- Error Validation -->
  </suite> <!-- Ecommerce Application -->
</testng-results>
